// <auto-generated />
using AutomobiliEvidencija.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutomobiliEvidencija.Migrations
{
    [DbContext(typeof(AutomobiliEvidencijaContext))]
    partial class AutomobiliEvidencijaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutomobiliEvidencija.Models.Automobil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Godina");

                    b.Property<string>("KonjskaSnaga");

                    b.Property<string>("Marka");

                    b.Property<string>("Model");

                    b.HasKey("ID");

                    b.ToTable("Automobil");
                });
#pragma warning restore 612, 618
        }
    }
}
